### ISSUE TITLE
Instructions to generate the compiler and openocd binaries.

### ISSUE THREAD

**Issue by crmoratelli** [hex-five/multizone-sdk#11]
There are no instructions about how to obtain the compiler or openocd binaries. After a while, I could generate all binaries from the own repository. The instructions to do that from a fresh ubuntu 18.04 install are:

1 - Install all system dependency packets:

sudo apt install build-essential git gawk texinfo bison flex libgmp-dev  libmpfr-dev libmpc-dev libexpat1-dev libtool automake libusb-1.0-0-dev minicom

2 - From the directory /multizone-sdk/riscv-gnu-toolchain generate the compiler:

./configure --enable-multilib   --prefix=<install dir>
make

3 - From the directory multizone-sdk/riscv-openocd generate the openocd:

./bootstrap
./configure --enable-ftdi --prefix=/home/crmoratelli/hexfive/riscv-openocd
make
make install

4 - Export the following variables:

export RISCV=<toolchain install dir>
export OPENOCD=<openocd install dir>

5 - You are ready to compile and load the multizone-sdk:

make
make load

**Comment by donbarnetson** [comment]
Got it - just to clarify this documentation is for the head of the sdk, not a specific branch and the scope of tool support we're targeting is Linux command line GNU only?

**Comment by cgarlati** [comment]
The MultiZone documentation should clearly point out that the multizone-sdk is certified to work with the reference GNU toolchain and openOCD provided as binary assetts of the GitHub release. See for example  the two tarballs at https://github.com/hex-five/multizone-sdk/releases. This is the piece of information that was missing and that led Carlos to build his own toolchain - with all related issues.

**Comment by donbarnetson** [comment]
Updated
