### ISSUE TITLE
wrong pmp configuration on zone's interrupt entry 

### ISSUE THREAD

**Issue by sandro2pinto** [hex-five/multizone-sdk#13]
I noticed the oneoff-sandro-irq branch (commit 8c58edb) has an issue related to a wrong PMP configuration (nanokernel context-switch) on a zone's interrupt entry - please make sure traps are registered so that it can be noticed.

---------- How to replicate:

/* Add trap 0x1 handler - Instruction Address Fault */

void trap_0x1_handler(void)__attribute__((interrupt("user")));
void trap_0x1_handler(void){
   ...
}

/* Register trap on main */ 
int main (void){
   ...
   ECALL_TRP_VECT(0x1, trap_0x1_handler); // 0x1 Instruction access fault
   ...
}

**Comment by cgarlati** [comment]
Fixed in 0a11fd1. Please test thourogly and eventually close. Thanks! Cesare
