### ISSUE TITLE
Zone4 stats are cast as integers, resulting in negative numbers

### ISSUE THREAD

**Issue by borancar** [hex-five/multizone-sdk#15]
https://github.com/hex-five/multizone-sdk/blob/210de0a9cd6399ad5e1f99526413f6483643b97e/zone4/main.c#L198

https://github.com/hex-five/multizone-sdk/blob/210de0a9cd6399ad5e1f99526413f6483643b97e/zone4/main.c#L205

https://github.com/hex-five/multizone-sdk/blob/210de0a9cd6399ad5e1f99526413f6483643b97e/zone4/main.c#L219

https://github.com/hex-five/multizone-sdk/blob/210de0a9cd6399ad5e1f99526413f6483643b97e/zone4/main.c#L225

**Comment by cgarlati** [comment]
Please move to hex-five/multizone-secure-iot-stack
