### ISSUE TITLE
Restarting zone1 over telnet can lead to zone1 locking up

### ISSUE THREAD

**Issue by borancar** [hex-five/multizone-sdk#16]
Reported against:  https://github.com/hex-five/multizone-sdk/commit/7edf433546d940b895c8d3aca0750fc86402c853

I experience a semi-random behavior when trying to restart zone1 over telnet. Zone2 remains functional as I can ping it still. LD0 and LD1 stop doing anything and stats show times < 10ms which indicates no tasks running in zone1.

Here are steps how to reproduce:
```
➜  ~ telnet 192.168.1.2
Trying 192.168.1.2...
Connected to 192.168.1.2.
Escape character is '^]'.

FreeRTOS CLI

Z1 > restart

FreeRTOS CLI

Z1 > restart

FreeRTOS CLI

Z1 > restart

FreeRTOS CLI

Z1 > restart

FreeRTOS CLI

Z1 > restart

FreeRTOS CLI

Z1 > restart
```

**Comment by cgarlati** [comment]
Please move to hex-five/multizone-secure-iot-stack
