### ISSUE TITLE
PLIC interrupts were not implemented as part of the FreeRTOS move

### ISSUE THREAD

**Issue by borancar** [hex-five/multizone-sdk#17]
We used to have PLIC interrupt functionality, last commit where it was working was 7b94f9cba0c999fe9188de0ea72345f19fbaa24e. We didn't implement this functionality in commit a7606a726794460088a05c88b18b27c24077e3d2, believing CLIC should be enough. With 20/20 hindsight, it's good to demonstrate PLIC interrupts, too.

**Comment by sandro2pinto** [comment]
Already in the pipeline - it will be implemented soon.

**Comment by borancar** [comment]
Cool, here's the original commit that implemented the PLIC handling - https://github.com/hex-five/multizone-sdk/commit/2e252636e44fb103c204796be6e64e0838649121

**Comment by cgarlati** [comment]
Please move to hex-five/multizone-secure-iot-stack
