### ISSUE TITLE
Documentation: reference toolchain and openocd

### ISSUE THREAD

**Issue by cgarlati** [hex-five/multizone-sdk#23]
Add documentation for using reference toolchain and openocd as submodules have been removed from this repo.

**Comment by donbarnetson** [comment]
Updated manual is available in the multizone-sdk-manual repo; pdf is here:
https://github.com/hex-five/multizone-sdk-manual/blob/master/release/multizone_sdk_manual.pdf

**Comment by donbarnetson** [comment]
Updated link

https://github.com/hex-five/multizone-sdk-manual/blob/master/multizone-sdk/release/multizone_sdk_manual.pdf

**Comment by cgarlati** [comment]
Need to update again as the tarballs have been removed from MultiZone releases for licensing reason.

**Comment by cgarlati** [comment]
https://hex-five.com/developers/ probably a good candidate for:

- reference riscv-gnu-toolchain
- reference riscv-openocd
- reference x300 mcs
