### ISSUE TITLE
README Content is missing

### ISSUE THREAD

**Issue by cgarlati** [hex-five/multizone-sdk#24]

**Comment by donbarnetson** [comment]
Updated

**Comment by cgarlati** [comment]
Needs to be updated with reference to manual.pdf

**Comment by donbarnetson** [comment]
Can you link manual once you upload - I do not have write access.

**Comment by cgarlati** [comment]
@borancar @donbarnetson Boran, Can you please set up Don to submit PRs? So that we keep track of changes.
