### ISSUE TITLE
Zone 1 Splash Screen has wrong revision

### ISSUE THREAD

**Issue by donbarnetson** [hex-five/multizone-sdk#26]
Zone 1 splash screen still has revision 0.1.1; should be updated to 1.0 per release version.

**Comment by cgarlati** [comment]
Working on an automated way to embed git id & tag at build time - i.e. make

**Comment by cgarlati** [comment]
Temporarily removed version number while awaiting for an automatic way to pull and substitute the Git tag at build time.
