### ISSUE TITLE
Zone 3 functionality incomplete

### ISSUE THREAD

**Issue by donbarnetson** [hex-five/multizone-sdk#27]
Zone three is missing two pieces of functionality that make it usable without the robot:
Z1 > send 3 r | g | b - should cause the flashing LED to change color
Z1 > send 1 ping should result in Z3 > pong response

**Comment by cgarlati** [comment]
In general, zone3 (robot ctrl) should show some meaningful functionality even if the robotic arm is not connected / available. WIP ...

**Comment by cgarlati** [comment]
Fixed in 08ee9fb

Z1> send 3 red |  green | blue
Z1> send 3 ping

Note: enter message full string - not just 1st character
