### ISSUE TITLE
files from libhexfive in the root of the repo

### ISSUE THREAD

**Issue by borancar** [hex-five/multizone-sdk#31]
[hex-five/multizone-secure-iot-stack](https://github.com/hex-five/multizone-secure-iot-stack/tree/master) uses files from this repo inside the [ext/multizone](https://github.com/hex-five/multizone-secure-iot-stack/tree/master/ext/multizone) folder. It would be easier to track changes and use subtree or submodule concepts if the folders were similar - to that end, it would make sense to extract the files from the [libhexfive](https://github.com/hex-five/multizone-sdk/tree/master/libhexfive) folder into the root of the repo - [hex-five/multizone-sdk](https://github.com/hex-five/multizone-sdk).

**Comment by cgarlati** [comment]
Agree on being consistent across repos. Unclear to me whether exposing three files rather than one folder is the best option. Let's review with the Team.
