### ISSUE TITLE
Turning on robotic arm produces messages from zone 2

### ISSUE THREAD

**Issue by borancar** [hex-five/multizone-sdk#32]
### Details

Reported on: https://github.com/hex-five/multizone-sdk/commit/ba86fd33c96b9385922cd852f7c4ca3a5233d056
Bitstream: E31 v3p0

### Steps to reproduce

1. Compile and load multizone-sdk
2. Connect UART
3. Turn on robotic arm

### Expected results

```
Z3 > USB DEVICE ATTACH VID=0x1267 PID=0x0000
```

### Actual results

```
Z3 > USB DEVICE ATTACH VID=0x1267 PID=0x0000
Z2 > ???
```

**Comment by cgarlati** [comment]
Fixed in aa7a4ad
