### ISSUE TITLE
Can't ping zones

### ISSUE THREAD

**Issue by borancar** [hex-five/multizone-sdk#33]
### Details

Reported on: https://github.com/hex-five/multizone-sdk/commit/ba86fd33c96b9385922cd852f7c4ca3a5233d056
Bitstream: E31 v3p0

### Steps to reproduce

1. Compile and upload multizone-sdk
2. Connect UART
3. `send 1 p`
4. `send 2 p`
5. `send 3 p`

### Expected results

```
Z1 > send 1 p

Z1 > pong

Z1 > send 2 p

Z2 > pong

Z1 > send 3 p

Z3 > pong
```

### Actual results

```
Z1 > send 1 p

Z1 > send 2 p

Z1 > send 3 p
```

**Comment by cgarlati** [comment]
Fixed in aa7a4ad
