### ISSUE TITLE
Changing LD0 color doesn't work on S51

### ISSUE THREAD

**Issue by borancar** [hex-five/multizone-sdk#43]
Reported on: 0e5d4a83e0ecf851d920b6c4069bb02f6c19073d
Reproduced on boards: S51

### Description

Sending messages to zone3 to change the color has no effect.

### Steps to reproduce

```
Z1 > send 3 red

Z1 > send 3 gree

Z1 > send 3 blue
```

**Comment by borancar** [comment]
This could be related to https://github.com/hex-five/multizone-sdk/issues/41.

**Comment by borancar** [comment]
Narrowed down to an issue in the nanokernel (or documentation) - https://github.com/hex-five/multizone-sdk/tree/bug/send64. UART should print abcd but instead it prints ac.

**Comment by cgarlati** [comment]
Fixed in [d508f88](https://github.com/hex-five/multizone-sdk/commit/d508f889be9654233fd66ac45e8fa6d6ceda989d)
