### ISSUE TITLE
Support for Sifive u540

### ISSUE THREAD

**Issue by pankajjoshi347** [hex-five/multizone-sdk#46]
hi,
i am very new to linux security.I am using sifive's u540 hifive unleashed and want to test working of multizone on the same.But i am unable to do so ,steps i am following is
1)i have downloaded the pre-built toolchain from 
http://hex-five.com/download

2)tar -xvf riscv-gnu-toolchain-20181226.tar.xz
tar -xvf riscv-openocd-20181226.tar.xz
git clone https://github.com/hex-five/multizone-sdk
sudo apt-get install libusb-0.1-4
sudo apt-get install screen

3)sudo vi /etc/udev/rules.d/99-openocd.rules
# These are for the HiFive1 Board
SUBSYSTEM=="usb", ATTR{idVendor}=="0403",
ATTR{idProduct}=="6010", MODE="664", GROUP="plugdev"
SUBSYSTEM=="tty", ATTRS{idVendor}=="0403",
ATTRS{idProduct}=="6010", MODE="664", GROUP="plugdev"
# These are for the Olimex Debugger for use with E310 Arty Dev Kit
SUBSYSTEM=="usb", ATTR{idVendor}=="15ba",
ATTR{idProduct}=="002a", MODE="664", GROUP="plugdev"
SUBSYSTEM=="tty", ATTRS{idVendor}=="15ba",
ATTRS{idProduct}=="002a", MODE="664", GROUP="plugdev"

4) export RISCV=/home/embd/riscv-gnu-toolchain-20181226
export OPENOCD=/home/embd/riscv-openocd-20181226
export PATH="$PATH:/home/embd/riscv-gnu-toolchain-20181226/bin"

5) cd multizone-sdk/
make clean
make BOARD=u540
ake BOARD=U540
Makefile:34: *** recipe commences before first target.  Stop.

How use this for U540 can you help ??

**Comment by cgarlati** [comment]
This SDK is not for Linux. For Linux you need https://github.com/hex-five/multizone-linux
More info here https://hex-five.com/multizone-enclave-linux/
