### ISSUE TITLE
Which respository is the trusted execution environment of multizone?

### ISSUE THREAD

**Issue by hz1490919302** [hex-five/multizone-sdk#47]
Can multizone be used to protect docker containers? If so, how to achieve it

**Comment by cgarlati** [comment]
Hi Mike,
Yes, MultiZone can protect any software, including OSs and Hypervisors, running on a supported hardware platform - see list at [readme.md](https://github.com/hex-five/multizone-sdk/blob/master/README.md).

What is your target hardware?

**Comment by hz1490919302** [comment]
I was going to use the Sifive Hifive Unleashed development board a few days ago. But my seller suddenly said it was sold out. Now I try to use Amazon's cloud FPGA service Firesim as a simulated fpga.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Cesare Garlati"<notifications@github.com&gt;; 
发送时间: 2020年8月26日(星期三) 凌晨0:57
收件人: "hex-five/multizone-sdk"<multizone-sdk@noreply.github.com&gt;; 
抄送: "何卓"<1490919302@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [hex-five/multizone-sdk] Which respository is the trusted execution environment of multizone? (#47)





 
Hi Mike,
 Yes, MultiZone can protect any software, including OSs and Hypervisors, running on a supported hardware platform - see list at readme.md.
 
What is your target hardware?
