### ISSUE TITLE
nanoKernel code location/availability

### ISSUE THREAD

**Issue by AntonHermann** [hex-five/multizone-sdk#52]
Hey there,

on your website you mention that the MultiZone runtime is formally verifiable and written in Assembly. Is the code of this runtime publicly available anywhere? I wasn't able to find any further information on that.

Thanks in advance,
Anton

**Comment by cgarlati** [comment]
Hi Anton,

Yes: MultiZone runtime components are written 100% in assembly.

Yes: MultiZone runtime components are designed for formal verification - a bit like hw blocks.

MultiZone runtime components are protected by patents US 11,151,262 and PCT/US2019/038774 and available to Hex Five's commercial licensees upon request.

Cesare
