### ISSUE TITLE
RISCV with multizone

### ISSUE THREAD

**Issue by RamyaBoggaram** [hex-five/multizone-sdk#57]
I am student from Texas A&M university as my professor wanted to research on RISCV with multizone. To continue we started with the official website https://github.com/hex-five/multizone-sdk on our virtual box with ubuntu machine and we are trying to connect "Arty A7 100T" board. Now we want to find out if the board is still supported by the company and if not, what board should we purchase to be fully supported. So that we could reach our goal.

**Comment by Hex-Five-Labs** [comment]
Ramya:

Yes, both Arty A7 35T and 100T are supported platforms and in fact Hex Five's recomended reference devevelopment boards along with Hex Five's reference X300 bitstream.
