### ISSUE TITLE
multizone to verify zone linker scripts

### ISSUE THREAD

**Issue by borancar** [hex-five/multizone-sdk#6]
I would like the multizone tool to check my individual zone's linker script to confirm whether the memory or sections are actually allowed in the multizone configuration.

Suggested interaction (the -l flag specifies the linker script for the last passed zone):
```
$ java -jar multizone.jar zone1/zone1.hex -l zone1/flash.lds zone2/zone2.hex -l zone2/flash.lds zone3/zone3.hex -l zone3/flash.lds --arch=$(BOARD)

ERROR: zone1/flash.lds maps the following section which is not allowed in zone's configuration:
  ram   (wxa!ri) : ORIGIN = 0x80001000, LENGTH =  16K
Closest match is
  base = 0x80001000; size =    4K; rwx = rw # RAM
```

**Comment by cgarlati** [comment]
A more elegant solution would be to parse .elf instead of .hex + .lds. The crosscheck should also include rwx policy. TBD
